name: lint

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'

      - name: install deps
        run: yarn

      - name: run tsc to check
        uses: andoshin11/typescript-error-reporter-action@v1.0.2

      - name: run eslint
        uses: Maggi64/eslint-plus-action@master
        with:
          issueSummary: false
          includeGlob: pages/**/*,lib/**/*,components/**/*
