name: release post

on:
  push:
    branches:
      - post

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: fnkr/github-action-ghr@v1
        env:
          GHR_COMPRESS: gz
          GHR_PATH: ./
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}